
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 23 2025 14:08:24 IST (Jun 23 2025 08:38:24 UTC)

// Verification Directory fv/MultiPhaseClocks 

module MultiPhaseClocks(Clk, A, B, C, E);
  input Clk, A, B, C;
  output E;
  wire Clk, A, B, C;
  wire E;
  wire D, UNCONNECTED, n_0, n_1;
  dfnrq1 E_reg(.CP (Clk), .D (n_1), .Q (E));
  nd12d0 g27(.A1 (C), .A2 (D), .ZN (n_1));
  dfnfb1 D_reg(.CPN (Clk), .D (n_0), .Q (UNCONNECTED), .QN (D));
  an02d1 g29(.A1 (A), .A2 (B), .Z (n_0));
endmodule

