
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 26 2025 13:01:09 IST (Jun 26 2025 07:31:09 UTC)

// Verification Directory fv/sync_rst_flipflop 

module sync_rst_flipflop(clk, rst, d, q);
  input clk, rst, d;
  output q;
  wire clk, rst, d;
  wire q;
  wire n_0, n_1;
  dfnrq1 q_reg(.CP (clk), .D (n_1), .Q (q));
  nr02d0 g4(.A1 (n_0), .A2 (rst), .ZN (n_1));
  inv0d0 g5(.I (d), .ZN (n_0));
endmodule

