
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 26 2025 13:11:12 IST (Jun 26 2025 07:41:12 UTC)

// Verification Directory fv/inferred_latch 

module inferred_latch(en, d, q);
  input en, d;
  output q;
  wire en, d;
  wire q;
  lanhq1 q_reg(.E (en), .D (d), .Q (q));
endmodule

