
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 20 2025 18:17:23 IST (Jun 20 2025 12:47:23 UTC)

// Verification Directory fv/AsyncFlipFlop 

module AsyncFlipFlop(ClkA, Reset, Set, CurrentState, NextState);
  input ClkA, Reset, Set;
  input [3:0] CurrentState;
  output [3:0] NextState;
  wire ClkA, Reset, Set;
  wire [3:0] CurrentState;
  wire [3:0] NextState;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1;
  dfbfb1 \NextState_reg[3] (.CDN (n_0), .SDN (Reset), .CPN (ClkA), .D
       (CurrentState[3]), .Q (NextState[3]), .QN (UNCONNECTED));
  dfpfb1 \NextState_reg[2] (.SDN (n_1), .CPN (ClkA), .D
       (CurrentState[2]), .Q (NextState[2]), .QN (UNCONNECTED0));
  dfcfq1 \NextState_reg[1] (.CDN (n_1), .CPN (ClkA), .D
       (CurrentState[1]), .Q (NextState[1]));
  dfbfb1 \NextState_reg[0] (.CDN (Reset), .SDN (Set), .CPN (ClkA), .D
       (CurrentState[0]), .Q (NextState[0]), .QN (UNCONNECTED1));
  nd12d0 g38(.A1 (Set), .A2 (Reset), .ZN (n_0));
  an02d0 g39(.A1 (Reset), .A2 (Set), .Z (n_1));
endmodule

