
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 23 2025 14:06:19 IST (Jun 23 2025 08:36:19 UTC)

// Verification Directory fv/GreaterThan 

module GreaterThan(A, B, Z);
  input [3:0] A, B;
  output Z;
  wire [3:0] A, B;
  wire Z;
  wire n_0, n_1;
  oai22d1 g60(.A1 (n_1), .A2 (B[2]), .B1 (n_0), .B2 (B[3]), .ZN (Z));
  oaim21d1 g61(.A (A[0]), .B1 (n_0), .B2 (B[3]), .ZN (n_1));
  inv0d0 g62(.I (A[1]), .ZN (n_0));
endmodule

