
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 27 2025 15:40:48 IST (Jun 27 2025 10:10:48 UTC)

// Verification Directory fv/fifo 

module fifo(clk, rst_n, wr_en, rd_en, din, dout, full, empty);
  input clk, rst_n, wr_en, rd_en;
  input [7:0] din;
  output [7:0] dout;
  output full, empty;
  wire clk, rst_n, wr_en, rd_en;
  wire [7:0] din;
  wire [7:0] dout;
  wire full, empty;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [4:0] wr_ptr;
  wire [4:0] rd_ptr;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_34, n_35;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_254, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_270, n_271, n_272, n_273, n_274;
  wire n_275, n_276, n_277, n_278, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_285, n_286, n_287, n_288, n_289, n_290;
  wire n_291, n_292, n_293, n_294, n_295, n_296, n_297, n_299;
  wire n_300, n_301, n_302, n_303, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_311, n_312, n_313, n_314, n_315;
  wire n_316, n_317, n_318, n_319, n_320, n_321, n_322, n_323;
  wire n_328, n_329, n_330, n_331, n_332;
  dfnrq1 \dout_reg[0] (.CP (clk), .D (n_316), .Q (dout[0]));
  dfnrq1 \dout_reg[1] (.CP (clk), .D (n_322), .Q (dout[1]));
  dfnrq1 \dout_reg[3] (.CP (clk), .D (n_323), .Q (dout[3]));
  dfnrq1 \dout_reg[4] (.CP (clk), .D (n_317), .Q (dout[4]));
  dfnrq1 \dout_reg[5] (.CP (clk), .D (n_319), .Q (dout[5]));
  dfnrq1 \dout_reg[2] (.CP (clk), .D (n_320), .Q (dout[2]));
  dfnrq1 \dout_reg[6] (.CP (clk), .D (n_315), .Q (dout[6]));
  dfnrq1 \dout_reg[7] (.CP (clk), .D (n_318), .Q (dout[7]));
  aor211d1 g3872(.A (n_312), .B (n_304), .C1 (n_321), .C2 (\mem[15]
       [3]), .Z (n_323));
  aor211d1 g3867(.A (n_306), .B (n_302), .C1 (n_321), .C2 (\mem[15]
       [1]), .Z (n_322));
  aor211d1 g3871(.A (n_313), .B (n_310), .C1 (n_321), .C2 (\mem[15]
       [2]), .Z (n_320));
  aor211d1 g3868(.A (n_295), .B (n_290), .C1 (n_321), .C2 (\mem[15]
       [5]), .Z (n_319));
  aor211d1 g3869(.A (n_314), .B (n_307), .C1 (n_321), .C2 (\mem[15]
       [7]), .Z (n_318));
  aor211d1 g3866(.A (n_309), .B (n_303), .C1 (n_321), .C2 (\mem[15]
       [4]), .Z (n_317));
  aor211d1 g3865(.A (n_308), .B (n_305), .C1 (n_321), .C2 (\mem[15]
       [0]), .Z (n_316));
  aor211d1 g3870(.A (n_301), .B (n_311), .C1 (n_321), .C2 (\mem[15]
       [6]), .Z (n_315));
  dfnrq1 \mem_reg[12][2] (.CP (clk), .D (n_297), .Q (\mem[12] [2]));
  dfnrq1 \mem_reg[12][1] (.CP (clk), .D (n_299), .Q (\mem[12] [1]));
  dfnrq1 \mem_reg[12][0] (.CP (clk), .D (n_300), .Q (\mem[12] [0]));
  dfnrq1 \mem_reg[12][3] (.CP (clk), .D (n_296), .Q (\mem[12] [3]));
  dfnrq1 \mem_reg[12][6] (.CP (clk), .D (n_292), .Q (\mem[12] [6]));
  dfnrq1 \mem_reg[12][5] (.CP (clk), .D (n_293), .Q (\mem[12] [5]));
  dfnrq1 \mem_reg[12][4] (.CP (clk), .D (n_294), .Q (\mem[12] [4]));
  dfnrq1 \mem_reg[12][7] (.CP (clk), .D (n_291), .Q (\mem[12] [7]));
  dfnrq1 \mem_reg[13][4] (.CP (clk), .D (n_274), .Q (\mem[13] [4]));
  dfnrq1 \mem_reg[13][1] (.CP (clk), .D (n_272), .Q (\mem[13] [1]));
  dfnrq1 \mem_reg[13][2] (.CP (clk), .D (n_288), .Q (\mem[13] [2]));
  dfnrq1 \mem_reg[13][3] (.CP (clk), .D (n_273), .Q (\mem[13] [3]));
  dfnrq1 \mem_reg[13][0] (.CP (clk), .D (n_289), .Q (\mem[13] [0]));
  dfnrq1 \mem_reg[13][5] (.CP (clk), .D (n_275), .Q (\mem[13] [5]));
  dfnrq1 \mem_reg[13][6] (.CP (clk), .D (n_276), .Q (\mem[13] [6]));
  dfnrq1 \mem_reg[13][7] (.CP (clk), .D (n_277), .Q (\mem[13] [7]));
  dfnrq1 \mem_reg[14][4] (.CP (clk), .D (n_282), .Q (\mem[14] [4]));
  dfnrq1 \mem_reg[14][1] (.CP (clk), .D (n_279), .Q (\mem[14] [1]));
  dfnrq1 \mem_reg[14][2] (.CP (clk), .D (n_280), .Q (\mem[14] [2]));
  dfnrq1 \mem_reg[14][3] (.CP (clk), .D (n_281), .Q (\mem[14] [3]));
  dfnrq1 \mem_reg[14][0] (.CP (clk), .D (n_278), .Q (\mem[14] [0]));
  dfnrq1 \mem_reg[14][5] (.CP (clk), .D (n_283), .Q (\mem[14] [5]));
  dfnrq1 \mem_reg[14][6] (.CP (clk), .D (n_285), .Q (\mem[14] [6]));
  dfnrq1 \mem_reg[14][7] (.CP (clk), .D (n_286), .Q (\mem[14] [7]));
  nd04d1 g3881(.A1 (n_189), .A2 (n_100), .A3 (n_168), .A4 (n_101), .ZN
       (n_314));
  nd04d1 g3880(.A1 (n_171), .A2 (n_104), .A3 (n_176), .A4 (n_95), .ZN
       (n_313));
  dfnrq1 \mem_reg[8][5] (.CP (clk), .D (n_258), .Q (\mem[8] [5]));
  dfnrq1 \mem_reg[8][0] (.CP (clk), .D (n_265), .Q (\mem[8] [0]));
  dfnrq1 \mem_reg[8][1] (.CP (clk), .D (n_263), .Q (\mem[8] [1]));
  dfnrq1 \mem_reg[8][2] (.CP (clk), .D (n_261), .Q (\mem[8] [2]));
  dfnrq1 \mem_reg[8][3] (.CP (clk), .D (n_266), .Q (\mem[8] [3]));
  dfnrq1 \mem_reg[8][4] (.CP (clk), .D (n_257), .Q (\mem[8] [4]));
  dfnrq1 \mem_reg[8][7] (.CP (clk), .D (n_260), .Q (\mem[8] [7]));
  dfnrq1 \mem_reg[9][0] (.CP (clk), .D (n_262), .Q (\mem[9] [0]));
  dfnrq1 \mem_reg[9][1] (.CP (clk), .D (n_256), .Q (\mem[9] [1]));
  dfnrq1 \mem_reg[9][2] (.CP (clk), .D (n_254), .Q (\mem[9] [2]));
  dfnrq1 \mem_reg[9][3] (.CP (clk), .D (n_253), .Q (\mem[9] [3]));
  dfnrq1 \mem_reg[9][4] (.CP (clk), .D (n_252), .Q (\mem[9] [4]));
  dfnrq1 \mem_reg[9][5] (.CP (clk), .D (n_251), .Q (\mem[9] [5]));
  dfnrq1 \mem_reg[9][7] (.CP (clk), .D (n_249), .Q (\mem[9] [7]));
  dfnrq1 \mem_reg[10][0] (.CP (clk), .D (n_238), .Q (\mem[10] [0]));
  dfnrq1 \mem_reg[10][1] (.CP (clk), .D (n_237), .Q (\mem[10] [1]));
  dfnrq1 \mem_reg[10][3] (.CP (clk), .D (n_239), .Q (\mem[10] [3]));
  dfnrq1 \mem_reg[10][4] (.CP (clk), .D (n_271), .Q (\mem[10] [4]));
  dfnrq1 \mem_reg[10][5] (.CP (clk), .D (n_270), .Q (\mem[10] [5]));
  dfnrq1 \mem_reg[11][0] (.CP (clk), .D (n_248), .Q (\mem[11] [0]));
  dfnrq1 \mem_reg[11][1] (.CP (clk), .D (n_247), .Q (\mem[11] [1]));
  dfnrq1 \mem_reg[11][2] (.CP (clk), .D (n_245), .Q (\mem[11] [2]));
  dfnrq1 \mem_reg[11][3] (.CP (clk), .D (n_244), .Q (\mem[11] [3]));
  dfnrq1 \mem_reg[11][4] (.CP (clk), .D (n_243), .Q (\mem[11] [4]));
  dfnrq1 \mem_reg[11][5] (.CP (clk), .D (n_242), .Q (\mem[11] [5]));
  dfnrq1 \mem_reg[10][7] (.CP (clk), .D (n_267), .Q (\mem[10] [7]));
  nd04d1 g3877(.A1 (n_141), .A2 (n_190), .A3 (n_137), .A4 (n_140), .ZN
       (n_312));
  nd04d1 g3883(.A1 (n_125), .A2 (n_170), .A3 (n_105), .A4 (n_98), .ZN
       (n_311));
  nd04d1 g3884(.A1 (n_103), .A2 (n_99), .A3 (n_164), .A4 (n_131), .ZN
       (n_310));
  nd04d1 g3873(.A1 (n_123), .A2 (n_181), .A3 (n_121), .A4 (n_122), .ZN
       (n_309));
  nd04d1 g3885(.A1 (n_113), .A2 (n_169), .A3 (n_97), .A4 (n_102), .ZN
       (n_308));
  nd04d1 g3886(.A1 (n_108), .A2 (n_96), .A3 (n_167), .A4 (n_94), .ZN
       (n_307));
  nd04d1 g3874(.A1 (n_208), .A2 (n_185), .A3 (n_135), .A4 (n_136), .ZN
       (n_306));
  nd04d1 g3887(.A1 (n_194), .A2 (n_111), .A3 (n_173), .A4 (n_118), .ZN
       (n_305));
  nd04d1 g3888(.A1 (n_166), .A2 (n_163), .A3 (n_107), .A4 (n_93), .ZN
       (n_304));
  nd04d1 g3875(.A1 (n_206), .A2 (n_235), .A3 (n_134), .A4 (n_128), .ZN
       (n_303));
  nd04d1 g3876(.A1 (n_142), .A2 (n_178), .A3 (n_117), .A4 (n_116), .ZN
       (n_302));
  nd04d1 g3882(.A1 (n_172), .A2 (n_106), .A3 (n_187), .A4 (n_124), .ZN
       (n_301));
  mx02d1 g4073(.I0 (din[0]), .I1 (\mem[12] [0]), .S (n_328), .Z
       (n_300));
  mx02d1 g4074(.I0 (din[1]), .I1 (\mem[12] [1]), .S (n_328), .Z
       (n_299));
  mx02d1 g4075(.I0 (din[2]), .I1 (\mem[12] [2]), .S (n_328), .Z
       (n_297));
  mx02d1 g4076(.I0 (din[3]), .I1 (\mem[12] [3]), .S (n_328), .Z
       (n_296));
  nd04d1 g3878(.A1 (n_180), .A2 (n_114), .A3 (n_179), .A4 (n_115), .ZN
       (n_295));
  mx02d1 g4077(.I0 (din[4]), .I1 (\mem[12] [4]), .S (n_328), .Z
       (n_294));
  mx02d1 g4078(.I0 (din[5]), .I1 (\mem[12] [5]), .S (n_328), .Z
       (n_293));
  mx02d1 g4079(.I0 (din[6]), .I1 (\mem[12] [6]), .S (n_328), .Z
       (n_292));
  mx02d1 g4080(.I0 (din[7]), .I1 (\mem[12] [7]), .S (n_328), .Z
       (n_291));
  nd04d1 g3879(.A1 (n_109), .A2 (n_184), .A3 (n_112), .A4 (n_110), .ZN
       (n_290));
  dfnrq1 \mem_reg[9][6] (.CP (clk), .D (n_250), .Q (\mem[9] [6]));
  dfnrq1 \mem_reg[10][6] (.CP (clk), .D (n_268), .Q (\mem[10] [6]));
  dfnrq1 \mem_reg[10][2] (.CP (clk), .D (n_236), .Q (\mem[10] [2]));
  dfnrq1 \mem_reg[8][6] (.CP (clk), .D (n_259), .Q (\mem[8] [6]));
  dfnrq1 \mem_reg[11][6] (.CP (clk), .D (n_241), .Q (\mem[11] [6]));
  dfnrq1 \mem_reg[11][7] (.CP (clk), .D (n_240), .Q (\mem[11] [7]));
  mx02d1 g4001(.I0 (\mem[13] [0]), .I1 (din[0]), .S (n_287), .Z
       (n_289));
  dfnrq1 \mem_reg[3][1] (.CP (clk), .D (n_233), .Q (\mem[3] [1]));
  dfnrq1 \mem_reg[0][7] (.CP (clk), .D (n_159), .Q (\mem[0] [7]));
  dfnrq1 \mem_reg[1][0] (.CP (clk), .D (n_174), .Q (\mem[1] [0]));
  dfnrq1 \mem_reg[1][1] (.CP (clk), .D (n_196), .Q (\mem[1] [1]));
  dfnrq1 \mem_reg[1][2] (.CP (clk), .D (n_197), .Q (\mem[1] [2]));
  dfnrq1 \mem_reg[1][3] (.CP (clk), .D (n_198), .Q (\mem[1] [3]));
  dfnrq1 \mem_reg[1][4] (.CP (clk), .D (n_199), .Q (\mem[1] [4]));
  dfnrq1 \mem_reg[1][5] (.CP (clk), .D (n_201), .Q (\mem[1] [5]));
  dfnrq1 \mem_reg[1][7] (.CP (clk), .D (n_155), .Q (\mem[1] [7]));
  dfnrq1 \mem_reg[2][0] (.CP (clk), .D (n_211), .Q (\mem[2] [0]));
  dfnrq1 \mem_reg[2][1] (.CP (clk), .D (n_150), .Q (\mem[2] [1]));
  dfnrq1 \mem_reg[2][2] (.CP (clk), .D (n_214), .Q (\mem[2] [2]));
  dfnrq1 \mem_reg[2][3] (.CP (clk), .D (n_177), .Q (\mem[2] [3]));
  dfnrq1 \mem_reg[2][4] (.CP (clk), .D (n_218), .Q (\mem[2] [4]));
  dfnrq1 \mem_reg[2][5] (.CP (clk), .D (n_222), .Q (\mem[2] [5]));
  dfnrq1 \mem_reg[2][7] (.CP (clk), .D (n_229), .Q (\mem[2] [7]));
  dfnrq1 \mem_reg[3][0] (.CP (clk), .D (n_160), .Q (\mem[3] [0]));
  dfnrq1 \mem_reg[4][6] (.CP (clk), .D (n_188), .Q (\mem[4] [6]));
  dfnrq1 \mem_reg[3][3] (.CP (clk), .D (n_230), .Q (\mem[3] [3]));
  dfnrq1 \mem_reg[3][4] (.CP (clk), .D (n_228), .Q (\mem[3] [4]));
  dfnrq1 \mem_reg[3][5] (.CP (clk), .D (n_227), .Q (\mem[3] [5]));
  dfnrq1 \mem_reg[3][7] (.CP (clk), .D (n_223), .Q (\mem[3] [7]));
  dfnrq1 \mem_reg[4][0] (.CP (clk), .D (n_195), .Q (\mem[4] [0]));
  dfnrq1 \mem_reg[4][1] (.CP (clk), .D (n_191), .Q (\mem[4] [1]));
  dfnrq1 \mem_reg[4][2] (.CP (clk), .D (n_203), .Q (\mem[4] [2]));
  dfnrq1 \mem_reg[4][3] (.CP (clk), .D (n_207), .Q (\mem[4] [3]));
  dfnrq1 \mem_reg[4][4] (.CP (clk), .D (n_210), .Q (\mem[4] [4]));
  dfnrq1 \mem_reg[4][5] (.CP (clk), .D (n_212), .Q (\mem[4] [5]));
  dfnrq1 \mem_reg[4][7] (.CP (clk), .D (n_186), .Q (\mem[4] [7]));
  dfnrq1 \mem_reg[5][0] (.CP (clk), .D (n_149), .Q (\mem[5] [0]));
  dfnrq1 \mem_reg[5][1] (.CP (clk), .D (n_148), .Q (\mem[5] [1]));
  dfnrq1 \mem_reg[5][3] (.CP (clk), .D (n_145), .Q (\mem[5] [3]));
  dfnrq1 \mem_reg[5][4] (.CP (clk), .D (n_144), .Q (\mem[5] [4]));
  dfnrq1 \mem_reg[5][5] (.CP (clk), .D (n_143), .Q (\mem[5] [5]));
  dfnrq1 \mem_reg[6][0] (.CP (clk), .D (n_221), .Q (\mem[6] [0]));
  mx02d1 g4035(.I0 (\mem[13] [2]), .I1 (din[2]), .S (n_287), .Z
       (n_288));
  mx02d1 g4048(.I0 (\mem[14] [7]), .I1 (din[7]), .S (n_284), .Z
       (n_286));
  mx02d1 g4047(.I0 (\mem[14] [6]), .I1 (din[6]), .S (n_284), .Z
       (n_285));
  mx02d1 g4046(.I0 (\mem[14] [5]), .I1 (din[5]), .S (n_284), .Z
       (n_283));
  mx02d1 g4045(.I0 (\mem[14] [4]), .I1 (din[4]), .S (n_284), .Z
       (n_282));
  mx02d1 g4044(.I0 (\mem[14] [3]), .I1 (din[3]), .S (n_284), .Z
       (n_281));
  mx02d1 g4043(.I0 (\mem[14] [2]), .I1 (din[2]), .S (n_284), .Z
       (n_280));
  mx02d1 g4042(.I0 (\mem[14] [1]), .I1 (din[1]), .S (n_284), .Z
       (n_279));
  mx02d1 g4041(.I0 (\mem[14] [0]), .I1 (din[0]), .S (n_284), .Z
       (n_278));
  mx02d1 g4040(.I0 (\mem[13] [7]), .I1 (din[7]), .S (n_287), .Z
       (n_277));
  mx02d1 g4039(.I0 (\mem[13] [6]), .I1 (din[6]), .S (n_287), .Z
       (n_276));
  mx02d1 g4038(.I0 (\mem[13] [5]), .I1 (din[5]), .S (n_287), .Z
       (n_275));
  mx02d1 g4037(.I0 (\mem[13] [4]), .I1 (din[4]), .S (n_287), .Z
       (n_274));
  mx02d1 g4036(.I0 (\mem[13] [3]), .I1 (din[3]), .S (n_287), .Z
       (n_273));
  mx02d1 g4034(.I0 (\mem[13] [1]), .I1 (din[1]), .S (n_287), .Z
       (n_272));
  dfnrq1 \mem_reg[6][2] (.CP (clk), .D (n_217), .Q (\mem[6] [2]));
  dfnrq1 \mem_reg[3][6] (.CP (clk), .D (n_224), .Q (\mem[3] [6]));
  dfnrq1 \mem_reg[6][1] (.CP (clk), .D (n_220), .Q (\mem[6] [1]));
  dfnrq1 \mem_reg[0][3] (.CP (clk), .D (n_153), .Q (\mem[0] [3]));
  dfnrq1 \mem_reg[3][2] (.CP (clk), .D (n_232), .Q (\mem[3] [2]));
  dfnrq1 \mem_reg[0][4] (.CP (clk), .D (n_152), .Q (\mem[0] [4]));
  dfnrq1 \mem_reg[0][2] (.CP (clk), .D (n_154), .Q (\mem[0] [2]));
  dfnrq1 \mem_reg[2][6] (.CP (clk), .D (n_226), .Q (\mem[2] [6]));
  dfnrq1 \mem_reg[5][6] (.CP (clk), .D (n_162), .Q (\mem[5] [6]));
  dfnrq1 \mem_reg[5][2] (.CP (clk), .D (n_146), .Q (\mem[5] [2]));
  dfnrq1 \mem_reg[6][6] (.CP (clk), .D (n_215), .Q (\mem[6] [6]));
  dfnrq1 \mem_reg[0][5] (.CP (clk), .D (n_151), .Q (\mem[0] [5]));
  dfnrq1 \mem_reg[0][6] (.CP (clk), .D (n_234), .Q (\mem[0] [6]));
  dfnrq1 \mem_reg[6][7] (.CP (clk), .D (n_147), .Q (\mem[6] [7]));
  dfnrq1 \mem_reg[5][7] (.CP (clk), .D (n_165), .Q (\mem[5] [7]));
  dfnrq1 \mem_reg[6][5] (.CP (clk), .D (n_213), .Q (\mem[6] [5]));
  dfnrq1 \mem_reg[6][4] (.CP (clk), .D (n_216), .Q (\mem[6] [4]));
  dfnrq1 \mem_reg[1][6] (.CP (clk), .D (n_202), .Q (\mem[1] [6]));
  dfnrq1 \mem_reg[6][3] (.CP (clk), .D (n_175), .Q (\mem[6] [3]));
  dfnrq1 \mem_reg[0][0] (.CP (clk), .D (n_157), .Q (\mem[0] [0]));
  dfnrq1 \mem_reg[0][1] (.CP (clk), .D (n_156), .Q (\mem[0] [1]));
  mx02d1 g4093(.I0 (din[4]), .I1 (\mem[10] [4]), .S (n_332), .Z
       (n_271));
  mx02d1 g4094(.I0 (din[5]), .I1 (\mem[10] [5]), .S (n_332), .Z
       (n_270));
  mx02d1 g4095(.I0 (din[6]), .I1 (\mem[10] [6]), .S (n_332), .Z
       (n_268));
  mx02d1 g4096(.I0 (din[7]), .I1 (\mem[10] [7]), .S (n_332), .Z
       (n_267));
  mx02d1 g4116(.I0 (din[3]), .I1 (\mem[8] [3]), .S (n_264), .Z (n_266));
  mx02d1 g4113(.I0 (din[0]), .I1 (\mem[8] [0]), .S (n_264), .Z (n_265));
  mx02d1 g4114(.I0 (din[1]), .I1 (\mem[8] [1]), .S (n_264), .Z (n_263));
  mx02d1 g4121(.I0 (din[0]), .I1 (\mem[9] [0]), .S (n_331), .Z (n_262));
  mx02d1 g4115(.I0 (din[2]), .I1 (\mem[8] [2]), .S (n_264), .Z (n_261));
  mx02d1 g4120(.I0 (din[7]), .I1 (\mem[8] [7]), .S (n_264), .Z (n_260));
  mx02d1 g4119(.I0 (din[6]), .I1 (\mem[8] [6]), .S (n_264), .Z (n_259));
  mx02d1 g4118(.I0 (din[5]), .I1 (\mem[8] [5]), .S (n_264), .Z (n_258));
  mx02d1 g4117(.I0 (din[4]), .I1 (\mem[8] [4]), .S (n_264), .Z (n_257));
  dfnrq1 \mem_reg[15][0] (.CP (clk), .D (n_84), .Q (\mem[15] [0]));
  dfnrq1 \mem_reg[15][2] (.CP (clk), .D (n_85), .Q (\mem[15] [2]));
  dfnrq1 \mem_reg[15][3] (.CP (clk), .D (n_86), .Q (\mem[15] [3]));
  dfnrq1 \mem_reg[15][5] (.CP (clk), .D (n_88), .Q (\mem[15] [5]));
  dfnrq1 \mem_reg[15][6] (.CP (clk), .D (n_89), .Q (\mem[15] [6]));
  dfnrq1 \mem_reg[15][7] (.CP (clk), .D (n_91), .Q (\mem[15] [7]));
  dfnrq1 \mem_reg[15][1] (.CP (clk), .D (n_92), .Q (\mem[15] [1]));
  mx02d1 g4122(.I0 (din[1]), .I1 (\mem[9] [1]), .S (n_331), .Z (n_256));
  mx02d1 g4123(.I0 (din[2]), .I1 (\mem[9] [2]), .S (n_331), .Z (n_254));
  mx02d1 g4124(.I0 (din[3]), .I1 (\mem[9] [3]), .S (n_331), .Z (n_253));
  mx02d1 g4125(.I0 (din[4]), .I1 (\mem[9] [4]), .S (n_331), .Z (n_252));
  mx02d1 g4126(.I0 (din[5]), .I1 (\mem[9] [5]), .S (n_331), .Z (n_251));
  mx02d1 g4127(.I0 (din[6]), .I1 (\mem[9] [6]), .S (n_331), .Z (n_250));
  mx02d1 g4128(.I0 (din[7]), .I1 (\mem[9] [7]), .S (n_331), .Z (n_249));
  mx02d1 g4025(.I0 (din[0]), .I1 (\mem[11] [0]), .S (n_246), .Z
       (n_248));
  mx02d1 g4026(.I0 (din[1]), .I1 (\mem[11] [1]), .S (n_246), .Z
       (n_247));
  mx02d1 g4027(.I0 (din[2]), .I1 (\mem[11] [2]), .S (n_246), .Z
       (n_245));
  mx02d1 g4028(.I0 (din[3]), .I1 (\mem[11] [3]), .S (n_246), .Z
       (n_244));
  mx02d1 g4029(.I0 (din[4]), .I1 (\mem[11] [4]), .S (n_246), .Z
       (n_243));
  mx02d1 g4030(.I0 (din[5]), .I1 (\mem[11] [5]), .S (n_246), .Z
       (n_242));
  mx02d1 g4031(.I0 (din[6]), .I1 (\mem[11] [6]), .S (n_246), .Z
       (n_241));
  mx02d1 g4032(.I0 (din[7]), .I1 (\mem[11] [7]), .S (n_246), .Z
       (n_240));
  mx02d1 g4092(.I0 (din[3]), .I1 (\mem[10] [3]), .S (n_332), .Z
       (n_239));
  mx02d1 g4089(.I0 (din[0]), .I1 (\mem[10] [0]), .S (n_332), .Z
       (n_238));
  mx02d1 g4090(.I0 (din[1]), .I1 (\mem[10] [1]), .S (n_332), .Z
       (n_237));
  mx02d1 g4091(.I0 (din[2]), .I1 (\mem[10] [2]), .S (n_332), .Z
       (n_236));
  dfnrq1 \mem_reg[15][4] (.CP (clk), .D (n_87), .Q (\mem[15] [4]));
  aoi22d1 g4143(.A1 (n_193), .A2 (\mem[1] [4]), .B1 (n_192), .B2
       (\mem[2] [4]), .ZN (n_235));
  mx02d1 g4097(.I0 (din[6]), .I1 (\mem[0] [6]), .S (n_158), .Z (n_234));
  mx02d1 g4098(.I0 (\mem[3] [1]), .I1 (din[1]), .S (n_231), .Z (n_233));
  mx02d1 g4099(.I0 (\mem[3] [2]), .I1 (din[2]), .S (n_231), .Z (n_232));
  mx02d1 g4100(.I0 (\mem[3] [3]), .I1 (din[3]), .S (n_231), .Z (n_230));
  mx02d1 g4002(.I0 (\mem[2] [7]), .I1 (din[7]), .S (n_225), .Z (n_229));
  mx02d1 g4101(.I0 (\mem[3] [4]), .I1 (din[4]), .S (n_231), .Z (n_228));
  mx02d1 g4102(.I0 (\mem[3] [5]), .I1 (din[5]), .S (n_231), .Z (n_227));
  mx02d1 g4003(.I0 (\mem[2] [6]), .I1 (din[6]), .S (n_225), .Z (n_226));
  mx02d1 g4103(.I0 (\mem[3] [6]), .I1 (din[6]), .S (n_231), .Z (n_224));
  mx02d1 g4104(.I0 (\mem[3] [7]), .I1 (din[7]), .S (n_231), .Z (n_223));
  mx02d1 g4004(.I0 (\mem[2] [5]), .I1 (din[5]), .S (n_225), .Z (n_222));
  mx02d1 g4105(.I0 (\mem[6] [0]), .I1 (din[0]), .S (n_219), .Z (n_221));
  mx02d1 g4106(.I0 (\mem[6] [1]), .I1 (din[1]), .S (n_219), .Z (n_220));
  mx02d1 g4005(.I0 (\mem[2] [4]), .I1 (din[4]), .S (n_225), .Z (n_218));
  mx02d1 g4107(.I0 (\mem[6] [2]), .I1 (din[2]), .S (n_219), .Z (n_217));
  mx02d1 g4109(.I0 (\mem[6] [4]), .I1 (din[4]), .S (n_219), .Z (n_216));
  mx02d1 g4111(.I0 (\mem[6] [6]), .I1 (din[6]), .S (n_219), .Z (n_215));
  mx02d1 g4007(.I0 (\mem[2] [2]), .I1 (din[2]), .S (n_225), .Z (n_214));
  mx02d1 g4110(.I0 (\mem[6] [5]), .I1 (din[5]), .S (n_219), .Z (n_213));
  mx02d1 g4022(.I0 (din[5]), .I1 (\mem[4] [5]), .S (n_209), .Z (n_212));
  mx02d1 g4009(.I0 (\mem[2] [0]), .I1 (din[0]), .S (n_225), .Z (n_211));
  mx02d1 g4021(.I0 (din[4]), .I1 (\mem[4] [4]), .S (n_209), .Z (n_210));
  aoi22d1 g4138(.A1 (n_205), .A2 (\mem[5] [1]), .B1 (n_204), .B2
       (\mem[6] [1]), .ZN (n_208));
  mx02d1 g4020(.I0 (din[3]), .I1 (\mem[4] [3]), .S (n_209), .Z (n_207));
  aoi22d1 g4137(.A1 (n_205), .A2 (\mem[5] [4]), .B1 (n_204), .B2
       (\mem[6] [4]), .ZN (n_206));
  mx02d1 g4019(.I0 (din[2]), .I1 (\mem[4] [2]), .S (n_209), .Z (n_203));
  mx02d1 g4011(.I0 (\mem[1] [6]), .I1 (din[6]), .S (n_200), .Z (n_202));
  mx02d1 g4012(.I0 (\mem[1] [5]), .I1 (din[5]), .S (n_200), .Z (n_201));
  mx02d1 g4013(.I0 (\mem[1] [4]), .I1 (din[4]), .S (n_200), .Z (n_199));
  mx02d1 g4014(.I0 (\mem[1] [3]), .I1 (din[3]), .S (n_200), .Z (n_198));
  mx02d1 g4015(.I0 (\mem[1] [2]), .I1 (din[2]), .S (n_200), .Z (n_197));
  mx02d1 g4016(.I0 (\mem[1] [1]), .I1 (din[1]), .S (n_200), .Z (n_196));
  mx02d1 g4017(.I0 (din[0]), .I1 (\mem[4] [0]), .S (n_209), .Z (n_195));
  aoi22d1 g4131(.A1 (n_193), .A2 (\mem[1] [0]), .B1 (n_192), .B2
       (\mem[2] [0]), .ZN (n_194));
  mx02d1 g4018(.I0 (din[1]), .I1 (\mem[4] [1]), .S (n_209), .Z (n_191));
  aoi22d1 g4135(.A1 (n_183), .A2 (\mem[8] [3]), .B1 (n_182), .B2
       (\mem[7] [3]), .ZN (n_190));
  dfnrq1 \mem_reg[7][1] (.CP (clk), .D (n_81), .Q (\mem[7] [1]));
  dfnrq1 \mem_reg[7][3] (.CP (clk), .D (n_78), .Q (\mem[7] [3]));
  dfnrq1 \mem_reg[7][5] (.CP (clk), .D (n_76), .Q (\mem[7] [5]));
  dfnrq1 \mem_reg[7][6] (.CP (clk), .D (n_73), .Q (\mem[7] [6]));
  dfnrq1 \mem_reg[7][7] (.CP (clk), .D (n_74), .Q (\mem[7] [7]));
  dfnrq1 \mem_reg[7][2] (.CP (clk), .D (n_79), .Q (\mem[7] [2]));
  dfnrq1 \mem_reg[7][0] (.CP (clk), .D (n_82), .Q (\mem[7] [0]));
  aoi22d1 g4145(.A1 (n_205), .A2 (\mem[5] [7]), .B1 (n_204), .B2
       (\mem[6] [7]), .ZN (n_189));
  mx02d1 g4023(.I0 (din[6]), .I1 (\mem[4] [6]), .S (n_209), .Z (n_188));
  aoi22d1 g4146(.A1 (n_193), .A2 (\mem[1] [6]), .B1 (n_192), .B2
       (\mem[2] [6]), .ZN (n_187));
  mx02d1 g4024(.I0 (din[7]), .I1 (\mem[4] [7]), .S (n_209), .Z (n_186));
  aoi22d1 g4148(.A1 (n_193), .A2 (\mem[1] [1]), .B1 (n_192), .B2
       (\mem[2] [1]), .ZN (n_185));
  aoi22d1 g4149(.A1 (n_183), .A2 (\mem[8] [5]), .B1 (n_182), .B2
       (\mem[7] [5]), .ZN (n_184));
  aoi22d1 g4153(.A1 (n_183), .A2 (\mem[8] [4]), .B1 (n_182), .B2
       (\mem[7] [4]), .ZN (n_181));
  aoi22d1 g4156(.A1 (n_205), .A2 (\mem[5] [5]), .B1 (n_204), .B2
       (\mem[6] [5]), .ZN (n_180));
  aoi22d1 g4160(.A1 (n_193), .A2 (\mem[1] [5]), .B1 (n_192), .B2
       (\mem[2] [5]), .ZN (n_179));
  aoi22d1 g4163(.A1 (n_183), .A2 (\mem[8] [1]), .B1 (n_182), .B2
       (\mem[7] [1]), .ZN (n_178));
  mx02d1 g4006(.I0 (\mem[2] [3]), .I1 (din[3]), .S (n_225), .Z (n_177));
  aoi22d1 g4167(.A1 (n_193), .A2 (\mem[1] [2]), .B1 (n_192), .B2
       (\mem[2] [2]), .ZN (n_176));
  mx02d1 g4108(.I0 (\mem[6] [3]), .I1 (din[3]), .S (n_219), .Z (n_175));
  mx02d1 g4033(.I0 (\mem[1] [0]), .I1 (din[0]), .S (n_200), .Z (n_174));
  aoi22d1 g4170(.A1 (n_205), .A2 (\mem[5] [0]), .B1 (n_204), .B2
       (\mem[6] [0]), .ZN (n_173));
  aoi22d1 g4171(.A1 (n_205), .A2 (\mem[5] [6]), .B1 (n_204), .B2
       (\mem[6] [6]), .ZN (n_172));
  aoi22d1 g4172(.A1 (n_205), .A2 (\mem[5] [2]), .B1 (n_204), .B2
       (\mem[6] [2]), .ZN (n_171));
  aoi22d1 g4177(.A1 (n_183), .A2 (\mem[8] [6]), .B1 (n_182), .B2
       (\mem[7] [6]), .ZN (n_170));
  aoi22d1 g4178(.A1 (n_183), .A2 (\mem[8] [0]), .B1 (n_182), .B2
       (\mem[7] [0]), .ZN (n_169));
  aoi22d1 g4179(.A1 (n_193), .A2 (\mem[1] [7]), .B1 (n_192), .B2
       (\mem[2] [7]), .ZN (n_168));
  aoi22d1 g4185(.A1 (n_183), .A2 (\mem[8] [7]), .B1 (n_182), .B2
       (\mem[7] [7]), .ZN (n_167));
  aoi22d1 g4187(.A1 (n_193), .A2 (\mem[1] [3]), .B1 (n_192), .B2
       (\mem[2] [3]), .ZN (n_166));
  mx02d1 g4088(.I0 (\mem[5] [7]), .I1 (din[7]), .S (n_161), .Z (n_165));
  aoi22d1 g4190(.A1 (n_183), .A2 (\mem[8] [2]), .B1 (n_182), .B2
       (\mem[7] [2]), .ZN (n_164));
  aoi22d1 g4193(.A1 (n_205), .A2 (\mem[5] [3]), .B1 (n_204), .B2
       (\mem[6] [3]), .ZN (n_163));
  mx02d1 g4087(.I0 (\mem[5] [6]), .I1 (din[6]), .S (n_161), .Z (n_162));
  mx02d1 g4065(.I0 (\mem[3] [0]), .I1 (din[0]), .S (n_231), .Z (n_160));
  mx02d1 g4066(.I0 (din[7]), .I1 (\mem[0] [7]), .S (n_158), .Z (n_159));
  mx02d1 g4067(.I0 (din[0]), .I1 (\mem[0] [0]), .S (n_158), .Z (n_157));
  mx02d1 g4068(.I0 (din[1]), .I1 (\mem[0] [1]), .S (n_158), .Z (n_156));
  mx02d1 g4010(.I0 (\mem[1] [7]), .I1 (din[7]), .S (n_200), .Z (n_155));
  mx02d1 g4069(.I0 (din[2]), .I1 (\mem[0] [2]), .S (n_158), .Z (n_154));
  mx02d1 g4070(.I0 (din[3]), .I1 (\mem[0] [3]), .S (n_158), .Z (n_153));
  mx02d1 g4071(.I0 (din[4]), .I1 (\mem[0] [4]), .S (n_158), .Z (n_152));
  mx02d1 g4072(.I0 (din[5]), .I1 (\mem[0] [5]), .S (n_158), .Z (n_151));
  mx02d1 g4008(.I0 (\mem[2] [1]), .I1 (din[1]), .S (n_225), .Z (n_150));
  mx02d1 g4081(.I0 (\mem[5] [0]), .I1 (din[0]), .S (n_161), .Z (n_149));
  mx02d1 g4082(.I0 (\mem[5] [1]), .I1 (din[1]), .S (n_161), .Z (n_148));
  mx02d1 g4112(.I0 (\mem[6] [7]), .I1 (din[7]), .S (n_219), .Z (n_147));
  mx02d1 g4083(.I0 (\mem[5] [2]), .I1 (din[2]), .S (n_161), .Z (n_146));
  mx02d1 g4084(.I0 (\mem[5] [3]), .I1 (din[3]), .S (n_161), .Z (n_145));
  mx02d1 g4085(.I0 (\mem[5] [4]), .I1 (din[4]), .S (n_161), .Z (n_144));
  mx02d1 g4086(.I0 (\mem[5] [5]), .I1 (din[5]), .S (n_161), .Z (n_143));
  dfnrq1 \mem_reg[7][4] (.CP (clk), .D (n_77), .Q (\mem[7] [4]));
  aoi22d1 g4150(.A1 (n_139), .A2 (\mem[13] [1]), .B1 (n_138), .B2
       (\mem[14] [1]), .ZN (n_142));
  aoi22d1 g4130(.A1 (n_130), .A2 (\mem[12] [3]), .B1 (n_129), .B2
       (\mem[11] [3]), .ZN (n_141));
  aoi22d1 g4132(.A1 (n_139), .A2 (\mem[13] [3]), .B1 (n_138), .B2
       (\mem[14] [3]), .ZN (n_140));
  aoi22d1 g4133(.A1 (n_120), .A2 (\mem[9] [3]), .B1 (n_119), .B2
       (\mem[10] [3]), .ZN (n_137));
  aoi22d1 g4134(.A1 (n_127), .A2 (\mem[0] [1]), .B1 (n_126), .B2
       (dout[1]), .ZN (n_136));
  aoi22d1 g4136(.A1 (n_133), .A2 (\mem[4] [1]), .B1 (n_132), .B2
       (\mem[3] [1]), .ZN (n_135));
  aoi22d1 g4139(.A1 (n_133), .A2 (\mem[4] [4]), .B1 (n_132), .B2
       (\mem[3] [4]), .ZN (n_134));
  aoi22d1 g4140(.A1 (n_130), .A2 (\mem[12] [2]), .B1 (n_129), .B2
       (\mem[11] [2]), .ZN (n_131));
  aoi22d1 g4141(.A1 (n_127), .A2 (\mem[0] [4]), .B1 (n_126), .B2
       (dout[4]), .ZN (n_128));
  aoi22d1 g4142(.A1 (n_130), .A2 (\mem[12] [6]), .B1 (n_129), .B2
       (\mem[11] [6]), .ZN (n_125));
  aoi22d1 g4144(.A1 (n_127), .A2 (\mem[0] [6]), .B1 (n_126), .B2
       (dout[6]), .ZN (n_124));
  aoi22d1 g4147(.A1 (n_130), .A2 (\mem[12] [4]), .B1 (n_129), .B2
       (\mem[11] [4]), .ZN (n_123));
  aoi22d1 g4129(.A1 (n_139), .A2 (\mem[13] [4]), .B1 (n_138), .B2
       (\mem[14] [4]), .ZN (n_122));
  aoi22d1 g4151(.A1 (n_120), .A2 (\mem[9] [4]), .B1 (n_119), .B2
       (\mem[10] [4]), .ZN (n_121));
  aoi22d1 g4152(.A1 (n_127), .A2 (\mem[0] [0]), .B1 (n_126), .B2
       (dout[0]), .ZN (n_118));
  aoi22d1 g4154(.A1 (n_120), .A2 (\mem[9] [1]), .B1 (n_119), .B2
       (\mem[10] [1]), .ZN (n_117));
  aoi22d1 g4155(.A1 (n_130), .A2 (\mem[12] [1]), .B1 (n_129), .B2
       (\mem[11] [1]), .ZN (n_116));
  aoi22d1 g4157(.A1 (n_127), .A2 (\mem[0] [5]), .B1 (n_126), .B2
       (dout[5]), .ZN (n_115));
  aoi22d1 g4158(.A1 (n_133), .A2 (\mem[4] [5]), .B1 (n_132), .B2
       (\mem[3] [5]), .ZN (n_114));
  aoi22d1 g4159(.A1 (n_139), .A2 (\mem[13] [0]), .B1 (n_138), .B2
       (\mem[14] [0]), .ZN (n_113));
  aoi22d1 g4161(.A1 (n_120), .A2 (\mem[9] [5]), .B1 (n_119), .B2
       (\mem[10] [5]), .ZN (n_112));
  aoi22d1 g4162(.A1 (n_133), .A2 (\mem[4] [0]), .B1 (n_132), .B2
       (\mem[3] [0]), .ZN (n_111));
  aoi22d1 g4164(.A1 (n_130), .A2 (\mem[12] [5]), .B1 (n_129), .B2
       (\mem[11] [5]), .ZN (n_110));
  aoi22d1 g4165(.A1 (n_139), .A2 (\mem[13] [5]), .B1 (n_138), .B2
       (\mem[14] [5]), .ZN (n_109));
  aoi22d1 g4166(.A1 (n_130), .A2 (\mem[12] [7]), .B1 (n_129), .B2
       (\mem[11] [7]), .ZN (n_108));
  aoi22d1 g4189(.A1 (n_133), .A2 (\mem[4] [3]), .B1 (n_132), .B2
       (\mem[3] [3]), .ZN (n_107));
  aoi22d1 g4173(.A1 (n_133), .A2 (\mem[4] [6]), .B1 (n_132), .B2
       (\mem[3] [6]), .ZN (n_106));
  aoi22d1 g4174(.A1 (n_120), .A2 (\mem[9] [6]), .B1 (n_119), .B2
       (\mem[10] [6]), .ZN (n_105));
  aoi22d1 g4175(.A1 (n_133), .A2 (\mem[4] [2]), .B1 (n_132), .B2
       (\mem[3] [2]), .ZN (n_104));
  aoi22d1 g4176(.A1 (n_139), .A2 (\mem[13] [2]), .B1 (n_138), .B2
       (\mem[14] [2]), .ZN (n_103));
  aoi22d1 g4180(.A1 (n_130), .A2 (\mem[12] [0]), .B1 (n_129), .B2
       (\mem[11] [0]), .ZN (n_102));
  aoi22d1 g4181(.A1 (n_127), .A2 (\mem[0] [7]), .B1 (n_126), .B2
       (dout[7]), .ZN (n_101));
  aoi22d1 g4182(.A1 (n_133), .A2 (\mem[4] [7]), .B1 (n_132), .B2
       (\mem[3] [7]), .ZN (n_100));
  aoi22d1 g4183(.A1 (n_120), .A2 (\mem[9] [2]), .B1 (n_119), .B2
       (\mem[10] [2]), .ZN (n_99));
  aoi22d1 g4184(.A1 (n_139), .A2 (\mem[13] [6]), .B1 (n_138), .B2
       (\mem[14] [6]), .ZN (n_98));
  aoi22d1 g4186(.A1 (n_120), .A2 (\mem[9] [0]), .B1 (n_119), .B2
       (\mem[10] [0]), .ZN (n_97));
  aoi22d1 g4188(.A1 (n_120), .A2 (\mem[9] [7]), .B1 (n_119), .B2
       (\mem[10] [7]), .ZN (n_96));
  aoi22d1 g4169(.A1 (n_127), .A2 (\mem[0] [2]), .B1 (n_126), .B2
       (dout[2]), .ZN (n_95));
  aoi22d1 g4191(.A1 (n_139), .A2 (\mem[13] [7]), .B1 (n_138), .B2
       (\mem[14] [7]), .ZN (n_94));
  aoi22d1 g4192(.A1 (n_127), .A2 (\mem[0] [3]), .B1 (n_126), .B2
       (dout[3]), .ZN (n_93));
  mx02d1 g4194(.I0 (\mem[15] [1]), .I1 (din[1]), .S (n_90), .Z (n_92));
  mx02d1 g4195(.I0 (\mem[15] [7]), .I1 (din[7]), .S (n_90), .Z (n_91));
  mx02d1 g4196(.I0 (\mem[15] [6]), .I1 (din[6]), .S (n_90), .Z (n_89));
  mx02d1 g4197(.I0 (\mem[15] [5]), .I1 (din[5]), .S (n_90), .Z (n_88));
  mx02d1 g4198(.I0 (\mem[15] [4]), .I1 (din[4]), .S (n_90), .Z (n_87));
  mx02d1 g4199(.I0 (\mem[15] [3]), .I1 (din[3]), .S (n_90), .Z (n_86));
  mx02d1 g4200(.I0 (\mem[15] [2]), .I1 (din[2]), .S (n_90), .Z (n_85));
  mx02d1 g4201(.I0 (\mem[15] [0]), .I1 (din[0]), .S (n_90), .Z (n_84));
  nr02d1 g4223(.A1 (n_70), .A2 (n_329), .ZN (n_287));
  nr02d1 g4222(.A1 (n_69), .A2 (n_329), .ZN (n_284));
  mx02d1 g4202(.I0 (din[0]), .I1 (\mem[7] [0]), .S (n_80), .Z (n_82));
  mx02d1 g4203(.I0 (din[1]), .I1 (\mem[7] [1]), .S (n_80), .Z (n_81));
  mx02d1 g4204(.I0 (din[2]), .I1 (\mem[7] [2]), .S (n_80), .Z (n_79));
  mx02d1 g4205(.I0 (din[3]), .I1 (\mem[7] [3]), .S (n_80), .Z (n_78));
  mx02d1 g4206(.I0 (din[4]), .I1 (\mem[7] [4]), .S (n_80), .Z (n_77));
  mx02d1 g4207(.I0 (din[5]), .I1 (\mem[7] [5]), .S (n_80), .Z (n_76));
  mx02d1 g4209(.I0 (din[7]), .I1 (\mem[7] [7]), .S (n_80), .Z (n_74));
  mx02d1 g4208(.I0 (din[6]), .I1 (\mem[7] [6]), .S (n_80), .Z (n_73));
  nd02d1 g4214(.A1 (n_71), .A2 (n_72), .ZN (n_264));
  nd12d1 g4210(.A1 (n_67), .A2 (n_71), .ZN (n_246));
  nr02d1 g4212(.A1 (n_70), .A2 (n_68), .ZN (n_161));
  nr02d1 g4213(.A1 (n_69), .A2 (n_68), .ZN (n_219));
  nd12d1 g4211(.A1 (n_68), .A2 (n_72), .ZN (n_209));
  nr02d1 g4216(.A1 (n_67), .A2 (n_66), .ZN (n_231));
  nd12d1 g4219(.A1 (n_66), .A2 (n_72), .ZN (n_158));
  nr02d1 g4220(.A1 (n_69), .A2 (n_66), .ZN (n_225));
  nr02d1 g4232(.A1 (n_64), .A2 (n_65), .ZN (n_205));
  nr02d1 g4224(.A1 (n_70), .A2 (n_66), .ZN (n_200));
  nr02d1 g4246(.A1 (n_62), .A2 (n_65), .ZN (n_193));
  an02d1 g4249(.A1 (n_51), .A2 (n_63), .Z (n_183));
  nr02d1 g4252(.A1 (n_64), .A2 (n_53), .ZN (n_182));
  nr02d1 g4243(.A1 (wr_ptr[2]), .A2 (n_330), .ZN (n_71));
  an02d1 g4229(.A1 (n_56), .A2 (n_63), .Z (n_192));
  an02d1 g4230(.A1 (n_60), .A2 (n_63), .Z (n_127));
  nr02d1 g4234(.A1 (n_62), .A2 (n_61), .ZN (n_129));
  nr02d1 g4245(.A1 (n_62), .A2 (n_58), .ZN (n_120));
  nr02d1 g4244(.A1 (n_57), .A2 (n_61), .ZN (n_138));
  an02d1 g4233(.A1 (n_60), .A2 (n_55), .Z (n_133));
  nr02d1 g4256(.A1 (n_15), .A2 (n_330), .ZN (n_90));
  nr02d1 g4248(.A1 (n_2), .A2 (n_61), .ZN (n_119));
  nr02d1 g4250(.A1 (n_64), .A2 (n_58), .ZN (n_139));
  nr02d1 g4251(.A1 (n_57), .A2 (n_58), .ZN (n_130));
  an02d1 g4253(.A1 (n_56), .A2 (n_22), .Z (n_132));
  an02d1 g4254(.A1 (n_56), .A2 (n_55), .Z (n_204));
  nr02d1 g4247(.A1 (n_64), .A2 (n_61), .ZN (n_321));
  nd02d1 g4225(.A1 (n_54), .A2 (wr_ptr[2]), .ZN (n_68));
  nd02d1 g4242(.A1 (n_54), .A2 (n_17), .ZN (n_66));
  nd02d1 g4255(.A1 (n_54), .A2 (n_24), .ZN (n_80));
  inv0d0 g4258(.I (n_56), .ZN (n_53));
  inv0d0 g4267(.I (n_58), .ZN (n_51));
  inv0d0 g4259(.I (n_60), .ZN (n_65));
  nr03d1 g4265(.A1 (rd_ptr[3]), .A2 (rd_ptr[1]), .A3 (n_126), .ZN
       (n_60));
  nr03d1 g4264(.A1 (rd_ptr[3]), .A2 (n_50), .A3 (n_126), .ZN (n_56));
  nd03d1 g4274(.A1 (n_49), .A2 (n_50), .A3 (rd_ptr[3]), .ZN (n_58));
  nd03d1 g4266(.A1 (n_49), .A2 (rd_ptr[1]), .A3 (rd_ptr[3]), .ZN
       (n_61));
  nr02d1 g4262(.A1 (wr_ptr[3]), .A2 (n_35), .ZN (n_54));
  oai22d1 g4260(.A1 (n_45), .A2 (n_21), .B1 (n_44), .B2 (n_19), .ZN
       (n_48));
  oai22d1 g4217(.A1 (n_42), .A2 (n_29), .B1 (n_41), .B2 (n_8), .ZN
       (n_47));
  oai22d1 g4268(.A1 (n_45), .A2 (rd_ptr[0]), .B1 (n_44), .B2 (n_30),
       .ZN (n_46));
  oai22d1 g4261(.A1 (n_42), .A2 (n_25), .B1 (n_41), .B2 (n_4), .ZN
       (n_43));
  decrq1 \wr_ptr_reg[2] (.CDN (rst_n), .CP (clk), .D (n_18), .ENN
       (n_42), .Q (wr_ptr[2]));
  decrq1 \rd_ptr_reg[1] (.CDN (rst_n), .CP (clk), .D (n_7), .ENN
       (n_45), .Q (rd_ptr[1]));
  aon211d1 g4269(.A (n_34), .B (n_42), .C1 (n_69), .C2 (n_70), .ZN
       (n_40));
  oai22d1 g4270(.A1 (n_45), .A2 (n_27), .B1 (n_44), .B2 (n_9), .ZN
       (n_39));
  oai22d1 g4271(.A1 (n_45), .A2 (n_23), .B1 (n_44), .B2 (n_11), .ZN
       (n_38));
  oai22d1 g4273(.A1 (n_42), .A2 (wr_ptr[0]), .B1 (n_41), .B2 (n_0), .ZN
       (n_37));
  inv0d0 g4277(.I (n_126), .ZN (n_49));
  nd02d1 g4278(.A1 (n_41), .A2 (rst_n), .ZN (n_35));
  nd02d1 g4279(.A1 (n_44), .A2 (rst_n), .ZN (n_126));
  nd02d1 g4275(.A1 (n_42), .A2 (wr_ptr[1]), .ZN (n_34));
  inv0d0 g4282(.I (n_42), .ZN (n_41));
  inv0d0 g4280(.I (n_45), .ZN (n_44));
  nd12d1 g4281(.A1 (empty), .A2 (rd_en), .ZN (n_45));
  nd12d1 g4284(.A1 (full), .A2 (wr_en), .ZN (n_42));
  nr02d1 g4285(.A1 (n_14), .A2 (n_31), .ZN (empty));
  nr02d1 g4287(.A1 (n_13), .A2 (n_31), .ZN (full));
  oai211d1 g4289(.A (n_20), .B (n_5), .C1 (n_30), .C2 (wr_ptr[0]), .ZN
       (n_31));
  aoim22d1 g4272(.A1 (n_28), .A2 (wr_ptr[4]), .B1 (n_28), .B2
       (wr_ptr[4]), .Z (n_29));
  aoim22d1 g4283(.A1 (n_26), .A2 (rd_ptr[4]), .B1 (n_26), .B2
       (rd_ptr[4]), .Z (n_27));
  oai21d1 g4286(.A (n_28), .B1 (n_24), .B2 (wr_ptr[3]), .ZN (n_25));
  aoi221d1 g4291(.A (n_55), .B1 (n_22), .B2 (rd_ptr[1]), .C1
       (rd_ptr[2]), .C2 (n_50), .ZN (n_23));
  oai21d1 g4292(.A (n_26), .B1 (n_16), .B2 (rd_ptr[3]), .ZN (n_21));
  aoi211d1 g4293(.A (n_6), .B (n_12), .C1 (wr_ptr[3]), .C2 (n_19), .ZN
       (n_20));
  aoi21d1 g4295(.A (n_24), .B1 (n_67), .B2 (n_17), .ZN (n_18));
  nd02d1 g4288(.A1 (n_24), .A2 (wr_ptr[3]), .ZN (n_28));
  nd02d1 g4294(.A1 (n_16), .A2 (rd_ptr[3]), .ZN (n_26));
  inv0d0 g4290(.I (n_24), .ZN (n_15));
  inv0d0 g4296(.I (n_13), .ZN (n_14));
  oai22d1 g4301(.A1 (wr_ptr[2]), .A2 (n_11), .B1 (n_17), .B2
       (rd_ptr[2]), .ZN (n_12));
  nr02d1 g4297(.A1 (n_50), .A2 (n_64), .ZN (n_16));
  oai22d1 g4298(.A1 (wr_ptr[4]), .A2 (rd_ptr[4]), .B1 (n_9), .B2 (n_8),
       .ZN (n_13));
  nr02d1 g4299(.A1 (n_17), .A2 (n_67), .ZN (n_24));
  oai22d1 g4300(.A1 (rd_ptr[1]), .A2 (n_30), .B1 (n_50), .B2
       (rd_ptr[0]), .ZN (n_7));
  oai22d1 g4302(.A1 (wr_ptr[1]), .A2 (n_50), .B1 (n_1), .B2
       (rd_ptr[1]), .ZN (n_6));
  aoi22d1 g4303(.A1 (rd_ptr[3]), .A2 (n_4), .B1 (wr_ptr[0]), .B2
       (n_30), .ZN (n_5));
  inv0d0 g4312(.I (n_62), .ZN (n_22));
  inv0d0 g4309(.I (n_57), .ZN (n_55));
  inv0d0 g4304(.I (n_63), .ZN (n_2));
  nd02d1 g4313(.A1 (rd_ptr[2]), .A2 (n_30), .ZN (n_57));
  nd02d1 g4316(.A1 (n_11), .A2 (rd_ptr[0]), .ZN (n_62));
  nd02d1 g4315(.A1 (n_1), .A2 (wr_ptr[0]), .ZN (n_70));
  nd02d1 g4314(.A1 (wr_ptr[1]), .A2 (n_0), .ZN (n_69));
  nr02d1 g4305(.A1 (rd_ptr[0]), .A2 (rd_ptr[2]), .ZN (n_63));
  nd02d1 g4307(.A1 (wr_ptr[1]), .A2 (wr_ptr[0]), .ZN (n_67));
  nr02d1 g4306(.A1 (wr_ptr[0]), .A2 (wr_ptr[1]), .ZN (n_72));
  nd02d1 g4308(.A1 (rd_ptr[2]), .A2 (rd_ptr[0]), .ZN (n_64));
  inv0d0 g4322(.I (rd_ptr[1]), .ZN (n_50));
  inv0d0 g4320(.I (wr_ptr[2]), .ZN (n_17));
  dfcrb1 \rd_ptr_reg[3] (.CDN (rst_n), .CP (clk), .D (n_48), .Q
       (rd_ptr[3]), .QN (n_19));
  dfcrb1 \rd_ptr_reg[4] (.CDN (rst_n), .CP (clk), .D (n_39), .Q
       (rd_ptr[4]), .QN (n_9));
  dfcrb1 \wr_ptr_reg[0] (.CDN (rst_n), .CP (clk), .D (n_37), .Q
       (wr_ptr[0]), .QN (n_0));
  dfcrb1 \rd_ptr_reg[2] (.CDN (rst_n), .CP (clk), .D (n_38), .Q
       (rd_ptr[2]), .QN (n_11));
  dfcrb1 \wr_ptr_reg[3] (.CDN (rst_n), .CP (clk), .D (n_43), .Q
       (wr_ptr[3]), .QN (n_4));
  dfcrb1 \wr_ptr_reg[4] (.CDN (rst_n), .CP (clk), .D (n_47), .Q
       (wr_ptr[4]), .QN (n_8));
  dfcrb1 \wr_ptr_reg[1] (.CDN (rst_n), .CP (clk), .D (n_40), .Q
       (wr_ptr[1]), .QN (n_1));
  dfcrb1 \rd_ptr_reg[0] (.CDN (rst_n), .CP (clk), .D (n_46), .Q
       (rd_ptr[0]), .QN (n_30));
  nd12d1 g2(.A1 (n_329), .A2 (n_72), .ZN (n_328));
  nd12d1 g4489(.A1 (n_330), .A2 (wr_ptr[2]), .ZN (n_329));
  nd12d1 g4490(.A1 (n_35), .A2 (wr_ptr[3]), .ZN (n_330));
  nd12d1 g4491(.A1 (n_70), .A2 (n_71), .ZN (n_331));
  nd12d1 g4492(.A1 (n_69), .A2 (n_71), .ZN (n_332));
endmodule

