
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 26 2025 13:05:17 IST (Jun 26 2025 07:35:17 UTC)

// Verification Directory fv/async_rst_flipflop 

module async_rst_flipflop(clk, rst, d, q);
  input clk, rst, d;
  output q;
  wire clk, rst, d;
  wire q;
  wire n_0;
  dfcrq1 q_reg(.CDN (n_0), .CP (clk), .D (d), .Q (q));
  inv0d0 g4(.I (rst), .ZN (n_0));
endmodule

