
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jul  4 2025 15:25:53 IST (Jul  4 2025 09:55:53 UTC)

// Verification Directory fv/design_with_multipleclk 

module design_with_multipleclk(clk, en, rst_n, d, q);
  input clk, en, rst_n, d;
  output q;
  wire clk, en, rst_n, d;
  wire q;
  wire n_0, n_1, n_2, n_3, n_4, n_5, p;
  dfcrq1 q_reg(.CDN (rst_n), .CP (clk), .D (n_3), .Q (q));
  oaim22d1 g50(.A1 (p), .A2 (d), .B1 (p), .B2 (d), .ZN (n_4));
  oaim22d1 g51(.A1 (p), .A2 (n_2), .B1 (n_5), .B2 (n_2), .ZN (n_3));
  dfcrn1 p_reg(.CDN (rst_n), .CP (clk), .D (n_1), .QN (p));
  oaim22d1 g53(.A1 (n_0), .A2 (d), .B1 (n_0), .B2 (d), .ZN (n_1));
  inv0d0 g54(.I (en), .ZN (n_2));
  dfcfb1 n_reg(.CDN (rst_n), .CPN (clk), .D (n_4), .Q (n_5), .QN (n_0));
endmodule

